# Generated by Django 5.0 on 2025-10-15 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_remove_perfil_especialidades_delete_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(help_text='Indica un precio o escribe "A convenir", "Gratis", etc.', max_length=100)),
                ('categoria', models.CharField(choices=[('atencion_preventiva', 'Atención preventiva'), ('atencion_basica', 'Atención básica'), ('restaurativa_mayor', 'Atención restaurativa mayor'), ('odontologia_cosmetica', 'Odontología cosmética'), ('ortodoncia', 'Ortodoncia')], help_text='Selecciona la categoría del servicio que ofreces.', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='accounts.perfil')),
            ],
        ),
    ]
