# Generated by Django 5.0 on 2025-10-27 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_remove_perfil_especialidades_delete_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(help_text='Indica un precio p.e. 100.00 o escribe "A convenir", "Gratis", etc.', max_length=100)),
                ('categoria', models.CharField(choices=[('odontologia_general', 'Odontología General y Preventiva'), ('odontologia_restauradora', 'Odontología Restauradora'), ('endodoncia', 'Endodoncia'), ('periodoncia', 'Periodoncia'), ('prostodoncia', 'Prostodoncia (Rehabilitación Oral)'), ('cirugia_oral', 'Cirugía Oral Básica'), ('ortodoncia', 'Ortodoncia')], help_text='Selecciona la categoría del servicio que ofreces.', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ofertas_fotos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('disponible', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='accounts.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('telefono_paciente', models.CharField(max_length=20)),
                ('email_paciente', models.EmailField(blank=True, max_length=254, null=True)),
                ('consulta', models.TextField(blank=True, null=True)),
                ('atendida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='ofertas.oferta')),
            ],
        ),
    ]
