# Generated by Django 5.0 on 2025-10-27 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_atencion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora propuesta por el paciente para la cita.'),
        ),
    ]
