# Generated by Django 5.0 on 2025-10-15 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='categoria',
            field=models.CharField(choices=[('limpieza', 'Limpieza Dental'), ('blanqueamiento', 'Blanqueamiento Dental'), ('extraccion', 'Extracción Dental'), ('endodoncia', 'Endodoncia'), ('ortodoncia', 'Ortodoncia')], help_text='Selecciona la categoría del servicio que ofreces.', max_length=50),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio',
            field=models.CharField(help_text='Indica un precio p.e. C$ 100.00 o escribe "A convenir", "Gratis", etc.', max_length=100),
        ),
        migrations.CreateModel(
            name='ImagenOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ofertas_fotos/')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ofertas.oferta')),
            ],
        ),
    ]
