# Generated by Django 5.0 on 2025-10-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_oferta_disponible_alter_oferta_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ofertas_fotos/'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio',
            field=models.CharField(help_text='Indica un precio p.e. 100.00 o escribe "A convenir", "Gratis", etc.', max_length=100),
        ),
        migrations.DeleteModel(
            name='ImagenOferta',
        ),
    ]
