# Generated by Django 5.0 on 2025-10-24 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_oferta_imagen_alter_oferta_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('telefono_paciente', models.CharField(max_length=20)),
                ('correo_paciente', models.EmailField(blank=True, max_length=254)),
                ('fecha_cita', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='ofertas.oferta')),
            ],
        ),
    ]
