# Generated by Django 5.0 on 2025-10-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='correo_paciente',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_cita',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='oferta',
        ),
        migrations.AddField(
            model_name='cita',
            name='consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='email_paciente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
