# Generated by Django 5.0 on 2025-10-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_remove_cita_correo_paciente_remove_cita_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='estudiante',
            new_name='perfil',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='cita',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='categoria',
            field=models.CharField(choices=[('limpieza', 'Limpieza Dental'), ('blanqueamiento', 'Blanqueamiento Dental'), ('extraccion', 'Extracción Dental'), ('endodoncia', 'Endodoncia'), ('ortodoncia', 'Ortodoncia')], default='limpieza', max_length=100),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
