# Generated by Django 5.0 on 2025-10-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='universidad',
        ),
        migrations.AddField(
            model_name='perfil',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='perfil',
            name='escuela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='fotos_perfil/default.png', upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sobre_mi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='carnet_de_estudiante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='accounts.habilidad'),
        ),
    ]
