# Generated by Django 5.0 on 2025-10-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_habilidad_remove_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='escuela',
        ),
        migrations.AddField(
            model_name='perfil',
            name='universidad',
            field=models.CharField(blank=True, choices=[('UNAN_MANAGUA', 'Universidad Nacional Autónoma de Nicaragua (Managua)'), ('UNAN_LEON', 'Universidad Nacional Autónoma de Nicaragua (León)'), ('UAM', 'Universidad Americana (UAM)'), ('UCM', 'Universidad de Ciencias Médicas (UCM)'), ('FCM_HOSPITAL_MILITAR', 'Facultad de Ciencias Médicas del Hospital Militar')], max_length=100, null=True),
        ),
    ]
