# Generated by Django 5.0.4 on 2024-05-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_perfil_escuela_perfil_universidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilidad',
            new_name='Especialidad',
        ),
    ]
