# Generated by Django 5.0 on 2025-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_habilidad_to_especialidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='ubicacion',
            new_name='barrio',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='habilidades',
            new_name='especialidades',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='correo_profesional',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección específica de la clínica o consultorio.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='disponible_para_citas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='horarios_atencion',
            field=models.TextField(blank=True, help_text='Ej: Lunes a Viernes de 9am a 5pm', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel_academico',
            field=models.CharField(blank=True, choices=[('1_ANO', '1er Año'), ('2_ANO', '2do Año'), ('3_ANO', '3er Año'), ('4_ANO', '4to Año'), ('5_ANO', '5to Año'), ('EGRESADO', 'Egresado/Pasante'), ('ESPECIALISTA', 'Especialista')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono_clinica',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
