# Generated by Django 5.0 on 2025-10-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_ubicacion_perfil_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='carnet_de_estudiante',
            field=models.ImageField(blank=True, help_text='Sube una imagen de tu carnet de estudiante para verificación.', null=True, upload_to='carnets_estudiante/'),
        ),
    ]
