# Generated by Django 5.0 on 2025-10-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_perfil_carnet_de_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
    ]
