# Generated by Django 5.0 on 2025-10-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_perfil_barrio_remove_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='telefono_clinica',
            new_name='telefono_estudiante',
        ),
    ]
