# Generated by Django 5.0 on 2025-10-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_telefono_clinica_perfil_telefono_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='universidad',
        ),
    ]
