# Generated by Django 5.0 on 2025-10-14 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_perfil_universidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='especialidades',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
