# Generated by Django 5.0 on 2025-11-11 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_perfil_especialidades_delete_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(help_text='Tu nombre (se mostrará públicamente)', max_length=100)),
                ('puntuacion', models.IntegerField(help_text='Puntuación de 1 a 5 estrellas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(help_text='Escribe tu reseña aquí.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, help_text='Las reseñas no activas no se mostrarán públicamente.')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
